CREATE TABLESPACE tbs_vetcare
    DATAFILE 'C:\ORACLE\ORADATA\XE\tbs_vetcare.dbf'
    SIZE 50M
    AUTOEXTEND ON NEXT 10M
    MAXSIZE 500M;

CREATE USER vetcare
    IDENTIFIED BY vetcare123
    DEFAULT TABLESPACE tbs_vetcare
    TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE TO vetcare;
GRANT UNLIMITED TABLESPACE TO vetcare;